name: Build and publish Docker image
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - 'gradle/**'
      - 'plugin-config-example.yaml'
      - 'README.md'
    release:
       types:
         - 'published'

jobs:
  push_to_registry:
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dockerhub auth
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: michaelbui99/metis

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

